### ISSUE TITLE
wrong command

### ISSUE THREAD

**Issue by loadingyy** [hanane-djeddal/Attributed-IR#2]
python evaluate_Correstness_answer_with_citation.py --architcture {G/RTG-vanilla/RTG-query-gen} 
should be
python evaluate_correstness.py --architcture {G/RTG-vanilla/RTG-query-gen}

**Comment by loadingyy** [comment]
And the architcture lacks {RTG-gold}

**Comment by hanane-djeddal** [comment]
Thank you for pointing it out, the readme has been updated (as well as some additional code refactoring, feel free to pull the new changes!)
